/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        surface: '#f7f9fb',
        'surface-dim': '#d8dadc',
        'surface-bright': '#f7f9fb',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f2f4f6',
        'surface-container': '#eceef0',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        'on-surface': '#191c1e',
        'on-surface-variant': '#45464f',
        'inverse-surface': '#2d3133',
        'inverse-on-surface': '#eff1f3',
        outline: '#767680',
        'outline-variant': '#c6c5d1',
        'surface-tint': '#4d5b94',
        primary: '#132359',
        'on-primary': '#ffffff',
        'primary-container': '#2b3a70',
        'on-primary-container': '#97a6e3',
        'inverse-primary': '#b7c4ff',
        secondary: '#00658d',
        'on-secondary': '#ffffff',
        'secondary-container': '#2dbcfe',
        'on-secondary-container': '#004866',
        tertiary: '#1d292f',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#333f45',
        'on-tertiary-container': '#9daab1',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#dce1ff',
        'primary-fixed-dim': '#b7c4ff',
        'on-primary-fixed': '#03164d',
        'on-primary-fixed-variant': '#35447a',
        'secondary-fixed': '#c6e7ff',
        'secondary-fixed-dim': '#82cfff',
        'on-secondary-fixed': '#001e2d',
        'on-secondary-fixed-variant': '#004c6b',
        'tertiary-fixed': '#d7e4ec',
        'tertiary-fixed-dim': '#bbc8d0',
        'on-tertiary-fixed': '#111d23',
        'on-tertiary-fixed-variant': '#3c494f',
        background: '#f7f9fb',
        'on-background': '#191c1e',
        'surface-variant': '#e0e3e5',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'title-lg': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', fontWeight: '600', letterSpacing: '0.05em' }],
        'label-sm': ['11px', { lineHeight: '14px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.25rem',
        DEFAULT: '0.5rem',
        md: '0.75rem',
        lg: '1rem',
        xl: '1.5rem',
      },
      spacing: {
        'container-margin': '2rem',
        gutter: '1.5rem',
        'stack-sm': '0.5rem',
        'stack-md': '1rem',
        'stack-lg': '2rem',
        'section-gap': '3rem',
      },
      boxShadow: {
        card: '0px 4px 20px rgba(0, 0, 0, 0.05)',
        modal: '0px 10px 40px rgba(0, 0, 0, 0.1)',
      },
    },
  },
  plugins: [],
};
